UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jp' WHERE title = 'The Dark Knight';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg' WHERE title = 'Inception';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg' WHERE title = 'Interstellar';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png' WHERE title = 'Gladiator';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg' WHERE title = 'Dune';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg' WHERE title = 'Star Wars';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg' WHERE title = 'Avatar';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png' WHERE title = 'The Matrix';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png' WHERE title = 'Titanic';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg' WHERE title = 'Forrest Gump';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg' WHERE title = 'The Shawshank Redemption';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg' WHERE title = 'Jurassic Park';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg' WHERE title = 'The Avengers';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg' WHERE title = 'Black Panther';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg' WHERE title IN ('Avengers Endgame', 'Avengers: Endgame');
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg' WHERE title = 'The Lion King';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg' WHERE title = 'Frozen';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg' WHERE title = 'Toy Story';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg' WHERE title = 'Finding Nemo';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg' WHERE title = 'The Good the Bad and the Ugly';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg' WHERE title = 'Back to the Future';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/b/bb/Independence_day_movieposter.jpg' WHERE title = 'Independence Day';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg' WHERE title = 'E.T. the Extra-Terrestrial';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/a4/The_Sixth_Sense_poster.png' WHERE title = 'The Sixth Sense';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/4/40/Jaws_movie_poster.jpg' WHERE title = 'Jaws';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg' WHERE title = 'WALL-E';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg' WHERE title = 'Arrival';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg' WHERE title = 'The Martian';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png' WHERE title = 'Blade Runner 2049';
UPDATE movie_booking.movies SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/f6/Gravity_Poster.jpg' WHERE title = 'Gravity';
