export const theaterSeeds = [
  { name: 'Grand Cinema', location: 'Downtown', total_seats: 240 },
  { name: 'Galaxy Multiplex', location: 'City Center', total_seats: 240 },
  { name: 'CineSquare', location: 'Lake Road', total_seats: 240 },
  { name: 'Silver Screens', location: 'Mall Plaza', total_seats: 240 },
  { name: 'Star View', location: 'Riverside', total_seats: 240 },
];

export const movieSeeds = [
  {
    title: 'The Dark Knight',
    description: 'Batman faces the Joker in a thrilling battle for Gotham.',
    genre: 'Action',
    duration: 152,
    rating: 9.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
    release_date: '2024-01-01',
    status: 'now_showing',
  },
  {
    title: 'Inception',
    description: 'A skilled thief leads a team to plant an idea inside a dream.',
    genre: 'Sci-Fi',
    duration: 148,
    rating: 8.8,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
    release_date: '2024-01-02',
    status: 'now_showing',
  },
  {
    title: 'Interstellar',
    description: 'A team of astronauts travels through a wormhole to save humanity.',
    genre: 'Sci-Fi',
    duration: 169,
    rating: 8.7,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
    release_date: '2024-01-03',
    status: 'now_showing',
  },
  {
    title: 'Gladiator',
    description: 'A Roman general fights his way back for justice and freedom.',
    genre: 'Action',
    duration: 155,
    rating: 8.5,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png',
    release_date: '2024-01-04',
    status: 'now_showing',
  },
  {
    title: 'Dune',
    description: 'Paul Atreides steps into destiny on the desert planet Arrakis.',
    genre: 'Sci-Fi',
    duration: 155,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg',
    release_date: '2024-01-05',
    status: 'now_showing',
  },
  {
    title: 'Star Wars',
    description: 'A young hero joins the rebellion against a galactic empire.',
    genre: 'Sci-Fi',
    duration: 121,
    rating: 8.6,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg',
    release_date: '2024-01-06',
    status: 'now_showing',
  },
  {
    title: 'Avatar',
    description: 'A marine enters a distant world and chooses where he belongs.',
    genre: 'Sci-Fi',
    duration: 162,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg',
    release_date: '2024-01-07',
    status: 'now_showing',
  },
  {
    title: 'The Matrix',
    description: 'A programmer learns his reality is a simulation and fights back.',
    genre: 'Sci-Fi',
    duration: 136,
    rating: 8.7,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png',
    release_date: '2024-01-08',
    status: 'now_showing',
  },
  {
    title: 'Titanic',
    description: 'A love story unfolds aboard the ill-fated ocean liner.',
    genre: 'Drama',
    duration: 194,
    rating: 7.9,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png',
    release_date: '2024-01-09',
    status: 'now_showing',
  },
  {
    title: 'Forrest Gump',
    description: 'An ordinary man lives through extraordinary moments in history.',
    genre: 'Drama',
    duration: 142,
    rating: 8.8,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
    release_date: '2024-01-10',
    status: 'now_showing',
  },
  {
    title: 'The Shawshank Redemption',
    description: 'Hope survives inside prison walls over many long years.',
    genre: 'Drama',
    duration: 142,
    rating: 9.3,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
    release_date: '2024-01-11',
    status: 'now_showing',
  },
  {
    title: 'Jurassic Park',
    description: 'Scientists and visitors face chaos when cloned dinosaurs break free.',
    genre: 'Action',
    duration: 127,
    rating: 8.1,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg',
    release_date: '2024-01-12',
    status: 'now_showing',
  },
  {
    title: 'The Avengers',
    description: 'Earths mightiest heroes unite to stop a global invasion.',
    genre: 'Action',
    duration: 143,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg',
    release_date: '2024-01-13',
    status: 'now_showing',
  },
  {
    title: 'Black Panther',
    description: 'A king fights to protect Wakanda and its future.',
    genre: 'Action',
    duration: 134,
    rating: 7.3,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg',
    release_date: '2024-01-14',
    status: 'now_showing',
  },
  {
    title: 'Avengers Endgame',
    description: 'The Avengers make one final stand against Thanos.',
    genre: 'Action',
    duration: 181,
    rating: 8.4,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
    release_date: '2024-01-15',
    status: 'now_showing',
  },
  {
    title: 'The Lion King',
    description: 'A young lion prince returns to reclaim his kingdom.',
    genre: 'Animation',
    duration: 88,
    rating: 8.5,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg',
    release_date: '2024-01-16',
    status: 'now_showing',
  },
  {
    title: 'Frozen',
    description: 'Two sisters fight to save their kingdom from endless winter.',
    genre: 'Animation',
    duration: 102,
    rating: 7.4,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg',
    release_date: '2024-01-17',
    status: 'now_showing',
  },
  {
    title: 'Toy Story',
    description: 'A jealous cowboy doll meets a fearless space ranger.',
    genre: 'Animation',
    duration: 81,
    rating: 8.3,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg',
    release_date: '2024-01-18',
    status: 'now_showing',
  },
  {
    title: 'Finding Nemo',
    description: 'A clownfish crosses the ocean to find his son.',
    genre: 'Animation',
    duration: 100,
    rating: 8.1,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg',
    release_date: '2024-01-19',
    status: 'now_showing',
  },
  {
    title: 'The Good the Bad and the Ugly',
    description: 'Three gunmen race across the west in search of buried gold.',
    genre: 'Drama',
    duration: 161,
    rating: 8.9,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg',
    release_date: '2024-01-20',
    status: 'now_showing',
  },
  {
    title: 'Back to the Future',
    description: 'A teenager travels to the past and risks changing everything.',
    genre: 'Sci-Fi',
    duration: 116,
    rating: 8.5,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg',
    release_date: '2024-01-21',
    status: 'now_showing',
  },
  {
    title: 'Independence Day',
    description: 'Humanity fights back after a global alien invasion.',
    genre: 'Sci-Fi',
    duration: 145,
    rating: 7.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Independence_day_movieposter.jpg',
    release_date: '2024-01-22',
    status: 'now_showing',
  },
  {
    title: 'E.T. the Extra-Terrestrial',
    description: 'A boy befriends a stranded alien and helps him find home.',
    genre: 'Sci-Fi',
    duration: 115,
    rating: 7.9,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg',
    release_date: '2024-01-23',
    status: 'now_showing',
  },
  {
    title: 'The Sixth Sense',
    description: 'A child who sees dead people changes a therapists life.',
    genre: 'Thriller',
    duration: 107,
    rating: 8.2,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/a/a4/The_Sixth_Sense_poster.png',
    release_date: '2024-01-24',
    status: 'now_showing',
  },
  {
    title: 'Jaws',
    description: 'A seaside town is terrorized by a giant shark.',
    genre: 'Thriller',
    duration: 124,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Jaws_movie_poster.jpg',
    release_date: '2024-01-25',
    status: 'now_showing',
  },
  {
    title: 'WALL-E',
    description: 'A lonely robot on Earth discovers a mission that can save humanity.',
    genre: 'Animation',
    duration: 98,
    rating: 8.4,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg',
    release_date: '2024-01-26',
    status: 'now_showing',
  },
  {
    title: 'Arrival',
    description: 'A linguist tries to understand visitors who have arrived from space.',
    genre: 'Sci-Fi',
    duration: 116,
    rating: 7.9,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg',
    release_date: '2024-01-27',
    status: 'now_showing',
  },
  {
    title: 'The Martian',
    description: 'An astronaut stranded on Mars uses science to stay alive.',
    genre: 'Sci-Fi',
    duration: 144,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg',
    release_date: '2024-01-28',
    status: 'now_showing',
  },
  {
    title: 'Blade Runner 2049',
    description: 'A new blade runner uncovers a secret that could reshape society.',
    genre: 'Sci-Fi',
    duration: 164,
    rating: 8.0,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png',
    release_date: '2024-01-29',
    status: 'now_showing',
  },
  {
    title: 'Gravity',
    description: 'Two astronauts struggle to survive after disaster in orbit.',
    genre: 'Sci-Fi',
    duration: 91,
    rating: 7.7,
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/f/f6/Gravity_Poster.jpg',
    release_date: '2024-01-30',
    status: 'now_showing',
  },
];

const showtimePatterns = [
  ['10:00:00', '14:00:00', '19:00:00'],
  ['11:00:00', '15:00:00'],
  ['12:00:00', '17:00:00'],
  ['10:30:00', '15:30:00'],
  ['13:00:00', '18:00:00'],
  ['11:30:00', '16:30:00'],
];

export const createShowtimeSeeds = () =>
  movieSeeds.flatMap((movie, movieIndex) => {
    const pattern = showtimePatterns[movieIndex % showtimePatterns.length];
    const dayOffset = movieIndex % 6;

    return pattern.map((showTime, slotIndex) => ({
      movie_title: movie.title,
      theater_name: theaterSeeds[(movieIndex + slotIndex) % theaterSeeds.length].name,
      show_date_offset: dayOffset,
      show_time: showTime,
      available_seats: 80,
      price: 250,
      screen_number: slotIndex + 1,
    }));
  });
